#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface
\rm -f constant/triSurface/SimpleRocket*
\rm -f constant/extendedFeatureEdgeMesh/SimpleRocket*
\rm -f Cd Cl p.residual Forces

rm -rf 0 > /dev/null 2>&1

cleanCase

# Reset decomposeParDict
cp system/decomposeParDict.hierarchical system/decomposeParDict

# ----------------------------------------------------------------- end-of-file
